# Generated by Django 5.1.3 on 2024-11-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='age',
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
