# Generated by Django 5.1.3 on 2024-11-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_user_detail_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(choices=[(1, '2 Weeks'), (2, '3 Weeks'), (3, '1 Month'), (4, '2 Months')], default=4)),
                ('tenant_type', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Family'), (4, 'None')], default=4)),
                ('location', models.IntegerField(choices=[(1, 'Airport'), (2, 'Banasree'), (3, 'Banani'), (4, 'Banani DOHS'), (5, 'Baridhara'), (6, 'Bashundhara Residential Area'), (7, 'Badda'), (8, 'Cantonment Area'), (9, 'Green Road'), (10, 'Gulshan'), (11, 'Mirpur'), (12, 'Mirpur DOHS'), (13, 'Nikunjo'), (14, 'Purbachal'), (15, 'Shaymoli'), (16, 'Uttara'), (17, 'Uttara Diabari')])),
                ('resident_type', models.IntegerField(choices=[(1, 'Apartment'), (2, 'Flat'), (3, 'Male Hostel'), (4, 'Female Hostel'), (5, 'Colony')])),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('rent', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('furnished', models.IntegerField(choices=[(1, 'Full Furnished'), (2, 'Not Furnished'), (3, 'Partially'), (4, 'None')], default=4)),
                ('security_deposit', models.CharField(choices=[('No Deposit', 'No Deposit'), ('Half Month Rent', 'Half Month Rent'), ('1 Month Rent', '1 Month Rent'), ('2 Months Rent', '2 Months Rent')], default='No Deposit', max_length=50)),
                ('lease_term', models.CharField(choices=[('No Lease', 'No Lease'), ('4 Months', '4 Months'), ('6 Months', '6 Months'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('Other', 'Other')], default='No Lease', max_length=50)),
                ('utilities_included', models.JSONField(blank=True, default=list)),
                ('non_included_bills', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
