# Generated by Django 5.1.3 on 2024-11-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_post_images_post_image1_post_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='resident_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='tenant_type',
            field=models.CharField(max_length=50),
        ),
    ]
