# Generated by Django 5.1.3 on 2024-11-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_post_location_alter_post_resident_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.IntegerField(choices=[(1, 'Airport'), (2, 'Banasree'), (3, 'Banani'), (4, 'Banani DOHS'), (5, 'Baridhara'), (6, 'Bashundhara Residential Area'), (7, 'Badda'), (8, 'Cantonment Area'), (9, 'Green Road'), (10, 'Gulshan'), (11, 'Mirpur'), (12, 'Mirpur DOHS'), (13, 'Nikunjo'), (14, 'Purbachal'), (15, 'Shaymoli'), (16, 'Uttara'), (17, 'Uttara Diabari')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='resident_type',
            field=models.IntegerField(choices=[(1, 'Apartment'), (2, 'Flat'), (3, 'Male Hostel'), (4, 'Female Hostel'), (5, 'Colony')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='tenant_type',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Family'), (4, 'None')], default=4),
        ),
    ]
