# Generated by Django 5.1.3 on 2024-11-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_post_id_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bed',
            field=models.IntegerField(choices=[(1, '1 Room'), (2, '2 Beds'), (3, '3 Beds'), (4, '4+ Beds'), (5, '1 Room'), (6, '2 Rooms'), (7, '3 Rooms'), (8, '4+ Rooms')], default=1010),
            preserve_default=False,
        ),
    ]
