# Generated by Django 5.1.3 on 2024-11-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_post_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='furnished',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='resident_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='tenant_type',
            field=models.CharField(max_length=100),
        ),
    ]
