# Generated by Django 5.1.3 on 2024-11-23 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_post_entry_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('post_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('tenant_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('bed', models.CharField(max_length=100)),
                ('resident_type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('rent', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('furnished', models.CharField(max_length=100)),
                ('security_deposit', models.CharField(choices=[('No Deposit', 'No Deposit'), ('Half Month Rent', 'Half Month Rent'), ('1 Month Rent', '1 Month Rent'), ('2 Months Rent', '2 Months Rent')], default='No Deposit', max_length=50)),
                ('lease_term', models.CharField(choices=[('No Lease', 'No Lease'), ('4 Months', '4 Months'), ('6 Months', '6 Months'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('Other', 'Other')], default='No Lease', max_length=50)),
                ('utilities_included', models.JSONField(blank=True, default=list)),
                ('non_included_bills', models.JSONField(blank=True, default=list)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
