# Generated by Django 5.1.3 on 2024-11-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_favorites_id_alter_favorites_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
