# Generated by Django 5.1.3 on 2024-11-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_user_detail_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
